# nale of workflow
name: My test workflow

# define trigger event
on: [push]

#jobs
jobs:
  say-hello:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello, actions"
  
  build-and-test:
    #needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y build-essential python3

      - run: pwd

      - name: Run test
        run: python3 test.py